// Generated by npm run build. Edit src/next-nc.js and src/fusion-adapter.js.
/* SPDX-License-Identifier: MIT
 * Original AP238 toolpath writer. ES5 syntax also runs inside Autodesk's post engine.
 */
var NextNC = (function () {
  "use strict";
  var VERSION = "0.3.0";
  var PROFILE = "next-nc/turning-toolpath/0.1";
  var MILL_PROFILE = "next-nc/milling-toolpath/0.1";
  var planes = {XY: {normal: [0, 0, 1], axes: [0, 1], fixed: 2}, XZ: {normal: [0, 1, 0], axes: [0, 2], fixed: 1}, YZ: {normal: [1, 0, 0], axes: [1, 2], fixed: 0}};
  function requireValue(ok, message) { if (!ok) { throw new Error("Next-NC: " + message); } }
  function finite(n, label) {
    requireValue(typeof n === "number" && isFinite(n) && Math.abs(n) < 1e15, label + " must be a finite number below 1e15 in magnitude");
    return n;
  }
  function positive(n, label) { finite(n, label); requireValue(n > 0, label + " must be positive"); return n; }
  function integer(n, label, minimum) {
    finite(n, label); requireValue(n === Math.floor(n) && n >= minimum, label + " must be an integer >= " + minimum); return n;
  }
  function point(p, machine) {
    requireValue(p && p.length === 3, "a point must have X, Y, Z coordinates");
    var q = [finite(p[0], "X"), finite(p[1], "Y"), finite(p[2], "Z")];
    if (machine !== "mill") { requireValue(Math.abs(q[1]) <= 1e-9, "only XZ turning with Y=0 is supported"); q[1] = 0; } return q;
  }
  function same(a, b) { return a[0] === b[0] && a[1] === b[1] && a[2] === b[2]; }
  function distance(a, b) { return Math.sqrt(Math.pow(a[0] - b[0], 2) + Math.pow(a[1] - b[1], 2) + Math.pow(a[2] - b[2], 2)); }
  function copySpindle(s) {
    requireValue(s && (s.mode === "rpm" || s.mode === "css"), "spindle mode must be rpm or css");
    requireValue(typeof s.clockwise === "boolean", "spindle direction must be explicit");
    var result = {mode: s.mode, speed: positive(s.speed, "spindle speed"), clockwise: s.clockwise};
    if (s.mode === "css") { result.maximumRPM = positive(s.maximumRPM, "CSS maximum RPM"); }
    return result;
  }
  function coolant(c) { requireValue(["off", "flood", "mist", "through tool"].indexOf(c) >= 0, "unsupported coolant: " + c); return c; }
  function feed(f) {
    requireValue(f && (f.mode === "perMinute" || f.mode === "perRevolution"), "feed mode must be perMinute or perRevolution");
    return {value: positive(f.value, "feed"), mode: f.mode};
  }
  function stateKey(s, f) {
    return [s.mode, s.speed, s.maximumRPM || 0, s.clockwise, f ? f.mode : "", f ? f.value : ""].join("|");
  }
  function Section(spec, machine) {
    this.machine = machine;
    requireValue(spec && spec.tool, "section and tool are required");
    this.name = String(spec.name || (machine === "mill" ? "Milling" : "Turning"));
    this.tool = {number: integer(spec.tool.number, "tool number", 1),
      offset: integer(spec.tool.offset, "tool offset", 0), description: String(spec.tool.description || "")};
    this.workOffset = integer(spec.workOffset, "Fusion work offset", 0);
    this.start = point(spec.start, machine);
    this.position = this.start.slice();
    this.setSpindle(spec.spindle);
    this.coolant = coolant(spec.coolant);
    this.initialSpindle = copySpindle(spec.spindle);
    this.initialCoolant = this.coolant;
    this.paths = [];
  }
  Section.prototype.setSpindle = function (s) {
    var spindle = copySpindle(s); requireValue(this.machine !== "mill" || spindle.mode === "rpm", "XYZ milling requires constant RPM"); this.spindle = spindle;
  };
  Section.prototype.setCoolant = function (c) { this.coolant = coolant(c); };
  Section.prototype.append = function (path, f) {
    path.spindle = copySpindle(this.spindle); path.coolant = this.coolant;
    path.feed = f ? feed(f) : null;
    path.key = path.kind + "|" + path.coolant + "|" + stateKey(path.spindle, path.feed);
    var previous = this.paths[this.paths.length - 1];
    // Compact only consecutive linear moves with identical process state.
    // Every intermediate vertex is preserved; this is not geometric smoothing.
    if ((path.kind === "rapid" || path.kind === "linear") && previous && previous.key === path.key) {
      previous.points.push(path.points[1]);
    } else { this.paths.push(path); }
  };
  Section.prototype.rapid = function (end) {
    end = point(end, this.machine);
    if (!same(this.position, end)) { this.append({kind: "rapid", points: [this.position, end]}); }
    this.position = end;
  };
  Section.prototype.linear = function (end, f) {
    end = point(end, this.machine); f = feed(f);
    if (!same(this.position, end)) { this.append({kind: "linear", points: [this.position, end]}, f); }
    this.position = end;
  };
  Section.prototype.arc = function (end, center, clockwise, f, fullCircle, plane) {
    end = point(end, this.machine); center = point(center, this.machine); f = feed(f);
    plane = plane || (this.machine === "mill" ? "XY" : "XZ");
    requireValue(Object.prototype.hasOwnProperty.call(planes, plane) && (this.machine === "mill" || plane === "XZ"), "unsupported arc plane");
    var frame = planes[plane];
    requireValue(this.position[frame.fixed] === end[frame.fixed] && center[frame.fixed] === end[frame.fixed], "arc must be planar; linearize helices in CAM");
    requireValue(typeof clockwise === "boolean", "arc direction must be explicit");
    var radius = positive(distance(this.position, center), "arc radius");
    var radialDifference = Math.abs(distance(end, center) - radius);
    if (radialDifference > Math.max(1e-7, radius * 1e-6)) {
      var arcError = new Error("Next-NC: arc endpoints have different radii");
      arcError.code = "ARC_RADII"; arcError.radialDifference = radialDifference;
      throw arcError;
    }
    requireValue(fullCircle ? same(this.position, end) : !same(this.position, end), "full-circle flag must match arc endpoints");
    this.append({kind: "arc", start: this.position, end: end, center: center, radius: radius,
      clockwise: clockwise, fullCircle: !!fullCircle, plane: plane}, f);
    this.position = end;
  };
  Section.prototype.dwell = function (seconds) { this.append({kind: "dwell", seconds: positive(seconds, "dwell")}); };
  function Program(options) {
    options = options || {};
    requireValue(options.units === "mm" || options.units === "inch", "units must be mm or inch");
    this.machine = options.machine || "lathe";
    requireValue(this.machine === "lathe" || this.machine === "mill", "machine must be lathe or mill");
    this.profile = this.machine === "mill" ? MILL_PROFILE : PROFILE;
    this.units = options.units; this.name = String(options.name || "Next-NC program");
    this.timestamp = options.timestamp || new Date().toISOString();
    requireValue(/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z$/.test(this.timestamp), "timestamp must be UTC ISO 8601");
    this.sections = [];
  }
  Program.prototype.addSection = function (spec) { var s = new Section(spec, this.machine); this.sections.push(s); return s; };
  function real(n) {
    finite(n, "STEP real");
    var result = (n === 0 ? "0" : String(n)).toUpperCase();
    if (result.indexOf("E") >= 0) {
      var parts = result.split("E"); if (parts[0].indexOf(".") < 0) { parts[0] += "."; }
      return parts[0] + "E" + parts[1];
    }
    return result.indexOf(".") >= 0 ? result : result + ".";
  }
  function str(value) {
    var s = String(value), result = "'", hex, code, i;
    for (i = 0; i < s.length; ++i) {
      code = s.charCodeAt(i);
      if (s[i] === "'") { result += "''"; }
      else if (s[i] === "\\") { result += "\\\\"; }
      else if (code >= 32 && code <= 126) { result += s[i]; }
      else {
        // Part 21 X2 encodes UTF-16 code units, including surrogate pairs.
        hex = code.toString(16).toUpperCase();
        if (code >= 0xD800 && code <= 0xDBFF) {
          var low = s.charCodeAt(++i);
          requireValue(low >= 0xDC00 && low <= 0xDFFF, "unpaired Unicode surrogate");
          hex += ("0000" + low.toString(16).toUpperCase()).slice(-4);
        } else { requireValue(code < 0xDC00 || code > 0xDFFF, "unpaired Unicode surrogate"); }
        result += "\\X2\\" + (hex.length < 4 ? ("0000" + hex).slice(-4) : hex) + "\\X0\\";
      }
    }
    return result + "'";
  }
  function list(items) { return "(" + items.join(",") + ")"; }
  // These records are immutable values. Never intern actions, paths, properties,
  // relationships or operations: equal fields do not imply equal execution.
  var sharedTypes = {
    CARTESIAN_POINT: true, DIRECTION: true, DESCRIPTIVE_REPRESENTATION_ITEM: true,
    MEASURE_REPRESENTATION_ITEM: true, REPRESENTATION: true, ACTION_RESOURCE_TYPE: true,
    MACHINING_FEED_SPEED_REPRESENTATION: true, MACHINING_SPINDLE_SPEED_REPRESENTATION: true,
    MACHINING_TOOLPATH_SPEED_PROFILE_REPRESENTATION: true, DERIVED_UNIT_ELEMENT: true,
    POLYLINE: true, AXIS2_PLACEMENT_3D: true, CIRCLE: true, TRIMMED_CURVE: true
  };
  function Writer(machine) {
    this.machine = machine; this.process = machine === "mill" ? "milling" : "turning";
    this.lines = []; this.valueCache = Object.create(null); this.reused = 0;
    this.curves = {polylines: 0, arcs: 0};
  }
  Writer.prototype.raw = function (value) { this.lines.push(value); return "#" + this.lines.length; };
  Writer.prototype.add = function (type, args) {
    var record = type + list(args);
    if (!Object.prototype.hasOwnProperty.call(sharedTypes, type)) { return this.raw(record); }
    if (this.valueCache[record]) { ++this.reused; return this.valueCache[record]; }
    if (type === "POLYLINE") { ++this.curves.polylines; }
    else if (type === "TRIMMED_CURVE") { ++this.curves.arcs; }
    var reference = this.raw(record); this.valueCache[record] = reference; return reference;
  };
  Writer.prototype.textItem = function (name, value) { return this.add("DESCRIPTIVE_REPRESENTATION_ITEM", [str(name), str(value)]); };
  Writer.prototype.point = function (p) { return this.add("CARTESIAN_POINT", ["''", list(p.map(real))]); };
  Writer.prototype.rep = function (type, name, items, context) { return this.add(type || "REPRESENTATION", [str(name), list(items), context || this.unitless]); };
  Writer.prototype.property = function (target, name, rep) {
    var prop = this.add("ACTION_PROPERTY", [str(name), "''", target]);
    this.add("ACTION_PROPERTY_REPRESENTATION", ["''", "''", prop, rep]);
  };
  Writer.prototype.textProperty = function (target, name, value) {
    this.property(target, name, this.rep(null, "", [this.textItem(name, value)]));
  };
  Writer.prototype.measure = function (name, value, unit) {
    return this.add("MEASURE_REPRESENTATION_ITEM", [str(name), "NUMERIC_MEASURE(" + real(value) + ")", unit]);
  };
  Writer.prototype.rel = function (kind, a, b, order) {
    var args = ["''", "''", a, b]; if (order !== undefined) { args.push(real(order)); }
    return this.add(kind, args);
  };
  Writer.prototype.method = function (type, name, description) { return this.add(type, [str(name), str(description || ""), "''", "''"]); };
  Writer.prototype.units = function (units) {
    this.unitless = this.add("REPRESENTATION_CONTEXT", ["''", str("units not necessary")]);
    this.length = this.raw("(LENGTH_UNIT() NAMED_UNIT(*) SI_UNIT(.MILLI.,.METRE.))");
    if (units === "inch") {
      var factor = this.add("LENGTH_MEASURE_WITH_UNIT", ["LENGTH_MEASURE(25.4)", this.length]);
      var dims = this.add("DIMENSIONAL_EXPONENTS", ["1.", "0.", "0.", "0.", "0.", "0.", "0."]);
      this.length = this.raw("(CONVERSION_BASED_UNIT('inch'," + factor + ") LENGTH_UNIT() NAMED_UNIT(" + dims + "))");
    }
    var angle = this.raw("(NAMED_UNIT(*) PLANE_ANGLE_UNIT() SI_UNIT($,.RADIAN.))");
    var solid = this.raw("(NAMED_UNIT(*) SI_UNIT($,.STERADIAN.) SOLID_ANGLE_UNIT())");
    this.context = this.raw("(GEOMETRIC_REPRESENTATION_CONTEXT(3) GLOBAL_UNIT_ASSIGNED_CONTEXT(" + list([this.length, angle, solid]) + ") REPRESENTATION_CONTEXT('','3D'))");
    this.second = this.raw("(NAMED_UNIT(*) SI_UNIT($,.SECOND.) TIME_UNIT())");
    var minuteFactor = this.add("TIME_MEASURE_WITH_UNIT", ["TIME_MEASURE(60.)", this.second]);
    var timeDims = this.add("DIMENSIONAL_EXPONENTS", ["0.", "0.", "1.", "0.", "0.", "0.", "0."]);
    var minute = this.raw("(CONVERSION_BASED_UNIT('minute'," + minuteFactor + ") NAMED_UNIT(" + timeDims + ") TIME_UNIT())");
    var zeroDims = this.add("DIMENSIONAL_EXPONENTS", ["0.", "0.", "0.", "0.", "0.", "0.", "0."]);
    var rev = this.add("CONTEXT_DEPENDENT_UNIT", [zeroDims, str("revolution")]);
    var self = this;
    function divided(a, b) {
      return self.add("DERIVED_UNIT", [list([self.add("DERIVED_UNIT_ELEMENT", [a, "1."]), self.add("DERIVED_UNIT_ELEMENT", [b, "-1."])])]);
    }
    this.rpm = divided(rev, minute); this.perMinute = divided(this.length, minute); this.perRevolution = divided(this.length, rev);
    this.technologyCache = {}; this.functionsCache = {};
  };
  Writer.prototype.technology = function (spindle, f) {
    var key = stateKey(spindle, f), cached = this.technologyCache[key]; if (cached) { return cached; }
    var tech = this.method("MACHINING_TECHNOLOGY", "", this.process), items;
    // AP238 uses a right-handed sign: clockwise is negative (opposite Fusion).
    var signed = spindle.speed * (spindle.clockwise ? -1 : 1);
    if (spindle.mode === "css") {
      items = [this.measure("surface speed", signed, this.perMinute), this.measure("maximum rotational speed", spindle.maximumRPM, this.rpm)];
    } else { items = [this.measure("rotational speed", signed, this.rpm)]; }
    this.property(tech, "spindle", this.rep("MACHINING_SPINDLE_SPEED_REPRESENTATION", spindle.mode === "css" ? "cutting speed" : "spindle speed", items));
    if (f) {
      var name = f.mode === "perMinute" ? "feed speed" : "feed per revolution";
      this.property(tech, "feedrate", this.rep("MACHINING_FEED_SPEED_REPRESENTATION", name, [this.measure(name, f.value, this[f.mode])]));
    }
    this.textProperty(tech, "feedrate reference", "tool center point");
    this.technologyCache[key] = tech; return tech;
  };
  Writer.prototype.functions = function (coolantMode) {
    var cached = this.functionsCache[coolantMode]; if (cached) { return cached; }
    var functions = this.method("MACHINING_FUNCTIONS", "", this.process);
    this.textProperty(functions, "coolant", coolantMode === "off" ? "coolant off" : "coolant on");
    if (coolantMode !== "off") { this.textProperty(functions, "coolant type", coolantMode); }
    this.functionsCache[coolantMode] = functions; return functions;
  };
  Writer.prototype.curve = function (path) {
    if (path.kind !== "arc") { return this.add("POLYLINE", ["''", list(path.points.map(this.point.bind(this)))]); }
    var normal = this.add("DIRECTION", ["''", list(planes[path.plane].normal.map(real))]);
    var direction = path.start.map(function (v, i) { return (v - path.center[i]) / path.radius; });
    var ref = this.add("DIRECTION", ["''", list(direction.map(real))]);
    var placement = this.add("AXIS2_PLACEMENT_3D", ["''", this.point(path.center), normal, ref]);
    var circle = this.add("CIRCLE", ["''", placement, real(path.radius)]);
    // +Y is the G18/ZX plane normal; counterclockwise is right-handed about +Y.
    var first = path.fullCircle ? "(PARAMETER_VALUE(0.))" : list([this.point(path.start)]);
    var last = path.fullCircle ? "(PARAMETER_VALUE(" + real(2 * Math.PI) + "))" : list([this.point(path.end)]);
    return this.add("TRIMMED_CURVE", ["''", circle, first, last, path.clockwise ? ".F." : ".T.", path.fullCircle ? ".PARAMETER." : ".CARTESIAN."]);
  };
  Writer.prototype.toolpath = function (operation, path, index) {
    var tp = this.method("MACHINING_TOOLPATH", "Path " + index, path.kind === "dwell" ? "feedstop" : "cutter location trajectory");
    this.rel("MACHINING_TOOLPATH_SEQUENCE_RELATIONSHIP", operation, tp, index);
    this.rel("MACHINING_TECHNOLOGY_RELATIONSHIP", tp, this.technology(path.spindle, path.feed));
    this.rel("MACHINING_FUNCTIONS_RELATIONSHIP", tp, this.functions(path.coolant));
    this.textProperty(tp, "priority", "required");
    if (path.kind === "dwell") {
      var time = this.add("MEASURE_REPRESENTATION_ITEM", [str("dwell"), "TIME_MEASURE(" + real(path.seconds) + ")", this.second]);
      this.property(tp, "dwell", this.rep(null, "", [time]));
    } else {
      this.textProperty(tp, "trajectory type", "trajectory path"); this.textProperty(tp, "direction", "beginning to end");
      this.property(tp, "basic curve", this.rep(null, "", [this.curve(path)], this.context));
      if (path.kind === "rapid") {
        this.property(tp, "speed profile", this.rep("MACHINING_TOOLPATH_SPEED_PROFILE_REPRESENTATION", "", [this.textItem("", "rapid")]));
      }
    }
  };
  Writer.prototype.project = function (program) {
    var app = this.add("APPLICATION_CONTEXT", [str("Application protocol for the exchange of CNC data")]);
    this.add("APPLICATION_PROTOCOL_DEFINITION", [str("international standard"), str("integrated_cnc_schema"), "2007", app]);
    var context = this.add("PRODUCT_CONTEXT", [str("CNC Machining"), app, str("manufacturing")]);
    var defContext = this.add("PRODUCT_DEFINITION_CONTEXT", [str("CNC Machining"), app, str("manufacturing")]);
    var project = this.add("MACHINING_PROJECT", [str(program.name), str(program.name), "$", list([context])]);
    var formation = this.add("PRODUCT_DEFINITION_FORMATION", [str(VERSION), "''", project]);
    var projectDef = this.add("PRODUCT_DEFINITION", ["''", "''", formation, defContext]);
    var workplan = this.method("MACHINING_WORKPLAN", program.name, "");
    var process = this.add("PRODUCT_DEFINITION_PROCESS", [str("machining"), "''", workplan, "''"]);
    this.add("PROCESS_PRODUCT_ASSOCIATION", ["''", "''", projectDef, process]);
    this.textProperty(workplan, "next-nc profile", program.profile);
    this.textProperty(workplan, "next-nc coordinates", program.machine === "mill" ? "WCS; XYZ Cartesian; fixed +Z tool axis; Fusion tool reference point" : "WCS; X radius; Y zero; Z axial; Fusion tool reference point");
    var part = this.add("PRODUCT", [str("workpiece"), str("Toolpath-only workpiece; geometry not supplied"), "$", list([context])]);
    var partFormation = this.add("PRODUCT_DEFINITION_FORMATION", ["''", "''", part]);
    var partDef = this.add("PRODUCT_DEFINITION", [str("workpiece"), "''", partFormation, defContext]);
    this.add("MACHINING_PROJECT_WORKPIECE_RELATIONSHIP", ["''", str("workpiece"), "''", projectDef, partDef]);
    this.partShape = this.add("PRODUCT_DEFINITION_SHAPE", ["''", "''", partDef]);
    return workplan;
  };
  Writer.prototype.section = function (workplan, section, index) {
    requireValue(section.paths.length > 0, "section '" + section.name + "' contains no motion or dwell");
    var ws = this.method("MACHINING_WORKINGSTEP", section.name, "machining");
    this.rel("MACHINING_PROCESS_SEQUENCE_RELATIONSHIP", workplan, ws, index);
    var operation = this.method(this.machine === "mill" ? "MILLING_TYPE_OPERATION" : "TURNING_TYPE_OPERATION", section.name, "");
    this.rel("MACHINING_OPERATION_RELATIONSHIP", ws, operation);
    // A generic CC1 toolpath feature avoids claiming feature-based turning geometry.
    var feature = this.add("INSTANCED_FEATURE", ["''", str("toolpath"), "''", str("toolpath"), this.partShape, ".T."]);
    var featureProcess = this.method("MACHINING_FEATURE_PROCESS", "", "machining");
    var process = this.add("PROPERTY_PROCESS", [str("machining"), "''", featureProcess, "''"]);
    this.add("PROCESS_PROPERTY_ASSOCIATION", ["''", str("machining"), process, feature]);
    this.rel("MACHINING_FEATURE_RELATIONSHIP", ws, featureProcess);
    // Logical tool reference, not an invented ISO turning-tool body/holder model.
    var toolType = this.add("ACTION_RESOURCE_TYPE", [str("cutting tool")]);
    this.add("MACHINING_TOOL", [str(section.tool.number), str(section.tool.description), list([operation]), toolType]);
    this.textProperty(operation, "next-nc tool offset", String(section.tool.offset));
    this.textProperty(operation, "next-nc work offset", String(section.workOffset));
    this.property(operation, "next-nc entry point", this.rep(null, "", [this.point(section.start)], this.context));
    this.rel("MACHINING_TECHNOLOGY_RELATIONSHIP", operation, this.technology(section.initialSpindle, null));
    this.rel("MACHINING_FUNCTIONS_RELATIONSHIP", operation, this.functions(section.initialCoolant));
    for (var i = 0; i < section.paths.length; ++i) { this.toolpath(operation, section.paths[i], i + 1); }
  };
  Program.prototype.toSTEP = function () {
    requireValue(this.sections.length > 0, "program contains no sections");
    var w = new Writer(this.machine); w.units(this.units); var workplan = w.project(this);
    for (var i = 0; i < this.sections.length; ++i) { w.section(workplan, this.sections[i], i + 1); }
    this.lastExport = {entities: w.lines.length, reusedValues: w.reused, curveDefinitions: w.curves, sections: this.sections.length,
      paths: 0, arcs: 0, rapidSegments: 0, cuttingSegments: 0, dwells: 0};
    for (i = 0; i < this.sections.length; ++i) {
      for (var j = 0; j < this.sections[i].paths.length; ++j) {
        var path = this.sections[i].paths[j]; ++this.lastExport.paths;
        if (path.kind === "arc") { ++this.lastExport.arcs; }
        else if (path.kind === "dwell") { ++this.lastExport.dwells; }
        else { this.lastExport[path.kind === "rapid" ? "rapidSegments" : "cuttingSegments"] += path.points.length - 1; }
      }
    }
    var lines = ["ISO-10303-21;", "HEADER;",
      "FILE_DESCRIPTION((" + str("Experimental AP238 toolpath; " + this.profile) + "),'2;1');",
      "FILE_NAME(" + str(this.name + ".stpnc") + "," + str(this.timestamp) + ",(''),('')," + str("Fusion360Next-NC " + VERSION) + ",'Fusion360Next-NC','');",
      "FILE_SCHEMA(('INTEGRATED_CNC_SCHEMA'));", "ENDSEC;", "DATA;"];
    for (i = 0; i < w.lines.length; ++i) { lines.push("#" + (i + 1) + "=" + w.lines[i] + ";"); }
    lines.push("ENDSEC;", "END-ISO-10303-21;"); return lines.join("\n") + "\n";
  };
  return {Program: Program, version: VERSION, profile: PROFILE, millingProfile: MILL_PROFILE, stepString: str, stepReal: real};
}());
if (typeof module !== "undefined" && module.exports) { module.exports = NextNC; }

/* SPDX-License-Identifier: MIT
 * Fusion callbacks. Bundled after next-nc.js to produce a standalone CPS.
 */
description = "Next-NC - experimental AP238 XZ turning / XYZ milling";
vendor = "Fusion360Next-NC";
vendorUrl = "https://github.com/markmounteer/Fusion360Next-NC";
legal = "Copyright (c) 2026 Mark Mounteer. MIT License.";
// Autodesk's configuration format version, NOT the Next-NC release number.
version = "1.0";
certificationLevel = 0;
minimumRevision = 45917;
extension = "stpnc";
longDescription = "Next-NC " + NextNC.version + ". Experimental toolpath-level STEP-NC/AP238 exporter for single-spindle XZ turning or fixed XYZ milling. Requires a Next-NC-aware consumer; LinuxCNC cannot load this file directly. No controller or machine options are duplicated here.";
capabilities = CAPABILITY_TURNING | CAPABILITY_MILLING;
setCodePage("ascii");
properties = {};
tolerance = spatial(0.002, MM);
minimumChordLength = spatial(0.001, MM);
minimumCircularRadius = spatial(0.001, MM);
maximumCircularRadius = spatial(100000, MM);
minimumCircularSweep = toRad(0.001);
maximumCircularSweep = 2 * Math.PI;
allowHelicalMoves = true; // Milling helices are linearized by Fusion at the operation tolerance.
allowSpiralMoves = false;
allowedCircularPlanes = (1 << PLANE_ZX) | (1 << PLANE_XY) | (1 << PLANE_YZ);

var nextProgram;
var nextSection;
var nextFeedMode;
var nextSpindle;
var nextFailed = false;
var nextOperationLabel = "";
var nextRecentEvents = [];
var nextEventCount = 0;
var nextStartedUTC = "";
var nextSectionDiagnostics = [];
var nextLinearizedArcs = 0;
var nextCycle;
var nextExpandedCyclePoints = 0;
var nextCycleTypes = [];
var nextCycleCuttingMoves = 0;
var nextSupportedCycles = ["drilling", "counter-boring", "chip-breaking", "deep-drilling"];

// Use the engine log: direct file access is restricted by Fusion's security
// level, and no callback can run when the engine rejects the global script.
function nextRead(read) {
  try { var value = read(); return value === undefined ? "unavailable" : value; }
  catch (e) { return "unavailable: " + String(e.message || e); }
}
function nextLog(message) {
  // Logging must never replace the original error or change export acceptance.
  try { log(message); } catch (e) { /* The engine still receives error(). */ }
}
function nextContext() {
  return {
    schema: "next-nc/diagnostic/1", release: NextNC.version, profile: nextProgram ? nextProgram.profile : "selected during precheck",
    configurationVersion: version, minimumRevision: minimumRevision, certificationLevel: certificationLevel,
    engine: nextRead(function () { return getVersion(); }),
    securityLevel: nextRead(function () { return getSecurityLevel(); }),
    configurationPath: nextRead(function () { return getConfigurationPath(); }),
    outputPath: nextRead(function () { return getOutputPath(); }),
    program: nextRead(function () { return programName; }), units: unit === MM ? "mm" : "inch",
    startedUTC: nextStartedUTC, sectionCount: nextRead(function () { return getNumberOfSections(); }),
    linearizedArcCount: nextLinearizedArcs, expandedCyclePoints: nextExpandedCyclePoints,
    cycle: nextCycle || null
  };
}
function nextSnapshot(section, index, issues) {
  return nextRead(function () {
    var t = section.getTool(), comp = nextCompensation(section);
    return {label: nextLabel(section, index), section: index + 1, type: section.getType(),
      tool: t.number, toolOffset: nextToolOffset(section, t), workOffset: section.workOffset,
      compensation: comp || "metadata missing; runtime guard active", feedMode: section.feedMode,
      strategy: nextRead(function () { return section.getStrategy(); }),
      entry: nextRead(function () { return nextPoint(section.getInitialPosition()); }),
      initialRPM: nextRead(function () { return section.getInitialSpindleSpeed(); }),
      operationTolerance: nextRead(function () { return section.getParameter("operation:tolerance"); }),
      cycleType: nextRead(function () { return section.hasAnyCycle() ? section.getParameter("operation:cycleType") : "none"; }),
      axisSubstitution: nextRead(function () { return nextSectionFlag(section, "getAxisSubstitution", "axisSubstitution"); }),
      dynamicWorkOffsetDefined: nextRead(function () { return nextSectionFlag(section, "hasDynamicWorkOffset"); }),
      dynamicWorkOffset: nextRead(function () { return section.getDynamicWorkOffset(); }),
      tailstock: nextRead(function () { return nextSectionFlag(section, "getTailstock", "tailstock"); }),
      partCatcher: nextRead(function () { return nextSectionFlag(section, "getPartCatcher", "partCatcher"); }),
      spindleMode: t.getSpindleMode(), surfaceSpeed: t.surfaceSpeed, maximumRPM: t.maximumSpindleSpeed,
      clockwise: t.clockwise, coolant: t.coolant,
      workPlane: {forward: nextPoint(section.workPlane.forward), right: nextPoint(section.workPlane.right)},
      issues: issues};
  });
}
function nextFail(e) {
  if (nextFailed) { error("Next-NC: export has already failed; see the first diagnostic."); return; }
  nextFailed = true;
  var message = String(e.message || e);
  try {
    var report = nextContext();
    report.status = "failed";
    report.failedUTC = new Date().toISOString();
    report.error = message;
    report.callback = nextRecentEvents.length ? nextRecentEvents[nextRecentEvents.length - 1].callback : "unknown";
    report.operation = nextOperationLabel || "No active operation (see section diagnostics)";
    report.record = nextRead(function () { return getCurrentRecordId(); });
    report.ncLocation = nextRead(function () { return getCurrentNCLocation(); });
    report.spindle = nextSpindle;
    report.feedMode = nextFeedMode;
    report.stack = e.stack || "not supplied by engine";
    report.callbackCount = nextEventCount;
    report.recentEvents = nextRecentEvents;
    report.sections = nextSectionDiagnostics;
    report.sectionSnapshotLimit = 200;
    report.outputStatus = "FAILED. Do not use the output; serialization/output may be incomplete.";
    nextLog("NEXTNC DIAGNOSTIC BEGIN\n" + JSON.stringify(report, null, 2) + "\nNEXTNC DIAGNOSTIC END");
  } catch (reportError) {
    nextLog("Next-NC diagnostic assembly failed: " + String(reportError.message || reportError) + "; original error: " + message);
  }
  error(message + "\n\nNext-NC " + NextNC.version + ": see the detailed report in Fusion's full post log. " +
    "With the Windows collector installed, reports are archived at %LOCALAPPDATA%\\Fusion360Next-NC\\diagnostics\\latest-error.txt.");
}
function nextCallback(name, callback) {
  return function () {
    if (nextFailed) { error("Next-NC: export has already failed; see the first diagnostic."); return; }
    ++nextEventCount;
    nextRecentEvents.push({callback: name, arguments: Array.prototype.slice.call(arguments),
      record: nextRead(function () { return getCurrentRecordId(); })});
    if (nextRecentEvents.length > 12) { nextRecentEvents.shift(); }
    try { return callback.apply(this, arguments); }
    catch (e) { if (nextFailed) { throw e; } nextFail(e); }
  };
}

function nextDiagnosticText(value) { return String(value).replace(/[\x00-\x1f\x7f]/g, " ").replace(/"/g, "'"); }
function nextLabel(section, index) {
  var name = nextRead(function () { return section.hasParameter("operation-comment") ? section.getParameter("operation-comment") : ""; });
  var number = nextRead(function () { return section.getTool().number; });
  return "Operation \"" + nextDiagnosticText(name || "Unnamed operation") + "\" (section " + (index + 1) +
    ", tool T" + nextDiagnosticText(number) + ")";
}
function nextCompensation(section) {
  // Missing metadata is not evidence of In computer. Keep the runtime guard active.
  if (!section.hasParameter("operation:compensationType")) { return null; }
  var value = section.getParameter("operation:compensationType");
  var names = {computer: "In computer", control: "In control", wear: "Wear", inverseWear: "Inverse wear", off: "Off"};
  var known = Object.prototype.hasOwnProperty.call(names, value);
  return {value: value, known: known, name: known ? names[value] : "unrecognized value \"" + nextDiagnosticText(value) + "\""};
}
function nextCompensationFix() {
  return "In Fusion, edit this operation > Passes > Compensation Type > In computer, regenerate its toolpath, then post again. " +
    "Do not select Off just to bypass this check; Off removes compensation.";
}
function nextPositive(value) { return typeof value === "number" && isFinite(value) && value > 0 && value < 1e15; }
function nextInteger(value, minimum) {
  return typeof value === "number" && isFinite(value) && value >= minimum && value < 1e15 && Math.floor(value) === value;
}
function nextSectionFlag(section, method, property) {
  var value = typeof section[method] === "function" ? section[method]() : (property ? section[property] : undefined);
  return value === undefined ? undefined : nextBoolean(value, "Fusion " + method);
}
function nextToolOffset(section, sectionTool) {
  return section.getType() === TYPE_MILLING ? sectionTool.lengthOffset : sectionTool.compensationOffset;
}
function nextSectionIssues(section) {
  var issues = [];
  var milling = section.getType() === TYPE_MILLING;
  if ((!milling && section.getType() !== TYPE_TURNING) || section.isMultiAxis()) {
    issues.push("[SECTION] Only fixed XZ turning or fixed XYZ milling is supported. Rotary/multi-axis operations are unsupported.");
  }
  if (section.isOptional()) { issues.push("[OPTIONAL] Optional sections are unsupported. Make this operation non-optional or exclude it."); }
  if (section.spindle !== SPINDLE_PRIMARY) { issues.push("[SPINDLE] Secondary-spindle operations are unsupported. Use a primary-spindle setup."); }
  var unsupported = [["getAxisSubstitution", "axisSubstitution", "AXIS_SUBSTITUTION", "Axis substitution"],
    ["getTailstock", "tailstock", "TAILSTOCK", "Tailstock control"],
    ["getPartCatcher", "partCatcher", "PART_CATCHER", "Part-catcher control"]];
  for (var f = 0; f < unsupported.length; ++f) {
    var flag = unsupported[f];
    if (nextSectionFlag(section, flag[0], flag[1])) {
      issues.push("[" + flag[2] + "] " + flag[3] + " is requested but cannot be represented by this Next-NC profile. " +
        "Use a post and consumer that support the required process; do not disable required equipment or coordinate transforms to bypass this check.");
    }
  }
  var wp = section.workPlane;
  if (!isSameDirection(wp.forward, new Vector(0, 0, 1)) || !isSameDirection(wp.right, new Vector(1, 0, 0))) {
    issues.push("[WORKPLANE] Rotated/mirrored work planes are unsupported. Use an unrotated work plane (+X right, +Z forward).");
  }
  var comp = nextCompensation(section);
  if (comp && comp.value !== "computer" && comp.value !== "off") {
    issues.push("[COMPENSATION] Compensation Type is " + comp.name + ". " +
      (comp.known ? "This requests controller-side compensation, which this post does not support. " : "This post cannot interpret that setting. ") +
      nextCompensationFix());
  }
  if (section.hasAnyCycle()) {
    var declaredCycle = section.hasParameter("operation:cycleType") ? section.getParameter("operation:cycleType") : undefined;
    if (!milling || (declaredCycle !== undefined && nextSupportedCycles.indexOf(declaredCycle) < 0)) {
      issues.push("[CYCLE] Canned cycles for turning and synchronized threading/tapping are unsupported. Only fixed XYZ milling drilling, counter-boring, chip-breaking and deep-drilling can be expanded by Fusion into explicit moves. Detected: " + nextDiagnosticText(declaredCycle || "cycle type unavailable") + ".");
    }
  }
  if (section.feedMode !== FEED_PER_MINUTE && section.feedMode !== FEED_PER_REVOLUTION) {
    issues.push("[FEED] Unsupported feed mode. Use feed per minute or feed per revolution.");
  }
  var sectionTool = section.getTool(), mode = sectionTool.getSpindleMode();
  if (!nextInteger(sectionTool.number, 1)) { issues.push("[TOOL_NUMBER] Set a positive integer tool number in Fusion's tool definition."); }
  if (!nextInteger(nextToolOffset(section, sectionTool), 0)) { issues.push("[TOOL_OFFSET] Set a nonnegative integer turning compensation offset or milling length offset in Fusion's tool definition."); }
  if (!nextInteger(section.workOffset, 0)) { issues.push("[WORK_OFFSET] Set a nonnegative integer WCS offset in the Fusion setup. Offset 0 remains unspecified and needs an explicit consumer mapping."); }
  if ([true, false, 0, 1].indexOf(sectionTool.clockwise) < 0) { issues.push("[DIRECTION] Fusion did not supply an explicit spindle direction. Review the tool/operation and regenerate it."); }
  var initial = section.getInitialPosition();
  if (!initial || [initial.x, initial.y, initial.z].some(function (v) { return typeof v !== "number" || !isFinite(v) || Math.abs(v) >= 1e15; })) {
    issues.push("[ENTRY] Fusion supplied an invalid initial position. Regenerate this operation's toolpath.");
  } else if (!milling && Math.abs(initial.y) > 1e-9) {
    issues.push("[ENTRY_Y] Initial Y is outside the supported zero-Y XZ plane. Review the setup/work plane and regenerate this operation.");
  }
  if (section.hasParameter("operation:tolerance") && !nextPositive(section.getParameter("operation:tolerance"))) {
    issues.push("[TOLERANCE] Fusion's operation tolerance must be a positive finite value. Review the operation and regenerate its toolpath.");
  }
  if (mode === SPINDLE_CONSTANT_SURFACE_SPEED) {
    if (milling) { issues.push("[SPINDLE_MODE] XYZ milling requires constant RPM; CSS is a turning-only mode."); }
    if (!nextPositive(sectionTool.surfaceSpeed)) { issues.push("[CSS_SPEED] Set a positive surface speed in the Fusion operation's Tool tab."); }
    if (!nextPositive(sectionTool.maximumSpindleSpeed)) { issues.push("[CSS_LIMIT] Set a positive maximum spindle speed for CSS in the Fusion operation's Tool tab."); }
  } else if (mode === SPINDLE_CONSTANT_SPINDLE_SPEED) {
    var initialRPM = section.getInitialSpindleSpeed();
    if (typeof initialRPM !== "number" || !nextPositive(Math.abs(initialRPM))) { issues.push("[RPM] Set a positive spindle RPM in the Fusion operation's Tool tab and regenerate the toolpath."); }
  } else {
    issues.push("[SPINDLE_MODE] Only constant RPM or constant surface speed is supported. Review the Fusion operation's spindle settings.");
  }
  if ([COOLANT_OFF, COOLANT_FLOOD, COOLANT_MIST, COOLANT_THROUGH_TOOL].indexOf(sectionTool.coolant) < 0) {
    issues.push("[COOLANT] Unsupported coolant selection. Supported modes are Off, Flood, Mist, and Through tool.");
  }
  return issues;
}
function nextPrecheck() {
  var problems = [], affected = 0, count = getNumberOfSections();
  if (!count) { throw new Error("Next-NC precheck: no machining sections selected. Select a turning or milling operation and post again."); }
  for (var i = 0; i < count; ++i) {
    var section = undefined, issues;
    try { section = getSection(i); issues = nextSectionIssues(section);
      if (section.getType() !== getSection(0).getType()) { issues.push("[MIXED_MACHINE] Post turning and milling setups as separate programs."); }
    }
    catch (e) { issues = ["[METADATA] Fusion section metadata could not be read: " + nextDiagnosticText(e.message || e) + ". Regenerate this operation and check the full diagnostic log."]; }
    if (nextSectionDiagnostics.length < 200) { nextSectionDiagnostics.push(nextSnapshot(section, i, issues)); }
    if (issues.length) {
      ++affected;
      problems.push(nextLabel(section, i) + ":\n  - " + issues.join("\n  - "));
    }
  }
  if (problems.length) {
    throw new Error("Next-NC " + NextNC.version + " precheck failed: " + affected + " of " + count + " section(s) need attention.\n\n" +
      problems.join("\n\n") + "\n\nNo STEP-NC program was written. Correct the listed settings and regenerate the affected toolpaths.");
  }
  nextLog("NEXTNC PRECHECK " + JSON.stringify({status: "passed", sectionsChecked: count,
    sections: nextSectionDiagnostics, sectionSnapshotLimit: 200,
    validation: "Fusion source metadata only; machine/tool-table compatibility and clearance are not checked."}));
}

function nextGuard(fn) {
  if (nextFailed) { error("Next-NC: export has already failed."); return; }
  try { return fn(); } catch (e) { if (nextFailed) { throw e; } nextFail(e); }
}
function nextReject(message) {
  nextFail(new Error("Next-NC: " + (nextOperationLabel ? nextOperationLabel + ": " : "") + message));
}
function nextPoint(p) { return [p.x, p.y, p.z]; }
function nextBoolean(value, label) {
  // Native callbacks can supply numeric flags even though the API says Boolean.
  // Normalize only the explicit 0/1 encodings; truthiness would hide bad input.
  if (value === true || value === 1) { return true; }
  if (value === false || value === 0) { return false; }
  throw new Error("Next-NC: " + label + " must be true/false or numeric 0/1; received " +
    nextDiagnosticText(value) + " (" + typeof value + ").");
}
function nextArcTolerance() {
  // Fusion owns the machining tolerance. Never loosen a tighter operation value.
  var limit = tolerance;
  if (hasParameter("operation:tolerance")) {
    var operationTolerance = getParameter("operation:tolerance");
    if (!nextPositive(operationTolerance)) { throw new Error("Next-NC: invalid Fusion operation tolerance for arc linearization."); }
    limit = Math.min(limit, operationTolerance);
  }
  return limit;
}
function nextFinishHelix(x, y, z, feed, limit) {
  var end = [x, y, z], position = nextSection.position, differs = false;
  for (var i = 0; i < 3; ++i) {
    // Native linearize() may end a few floating-point ulps from the callback
    // endpoint. Keep its vertices, then retain the exact supplied endpoint too.
    // This allowance is bounded far below the CAM tolerance, not a snap radius.
    var roundoff = Math.min(limit * 1e-6, Math.max(1, Math.abs(end[i]), Math.abs(position[i])) * 32 * 2.220446049250313e-16);
    if (Math.abs(position[i] - end[i]) > roundoff) { throw new Error("Next-NC: Fusion helix linearization did not reach its endpoint. Expected " + JSON.stringify(end) + "; received " + JSON.stringify(position) + "."); }
    differs = differs || position[i] !== end[i];
  }
  if (differs) { nextSection.linear(end, nextFeed(feed)); }
}
function nextFeed(value) { return {value: value, mode: nextFeedMode}; }
function nextSetFeedMode(mode) {
  if (mode === FEED_PER_MINUTE) { nextFeedMode = "perMinute"; }
  else if (mode === FEED_PER_REVOLUTION) { nextFeedMode = "perRevolution"; }
  else { nextReject("Inverse-time and unrecognized feed modes are unsupported."); }
}
function nextCoolant(mode) {
  if (mode === COOLANT_OFF) { return "off"; }
  if (mode === COOLANT_FLOOD) { return "flood"; }
  if (mode === COOLANT_MIST) { return "mist"; }
  if (mode === COOLANT_THROUGH_TOOL) { return "through tool"; }
  throw new Error("Next-NC: unsupported coolant mode " + mode);
}
function nextNeedSection() { if (!nextSection) { throw new Error("Next-NC: event outside a machining section"); } }
function onOpen() {
  nextGuard(function () {
    nextStartedUTC = new Date().toISOString();
    nextLog("NEXTNC START " + JSON.stringify(nextContext()));
    nextPrecheck();
    nextProgram = new NextNC.Program({name: programName || "Fusion machining", units: unit === MM ? "mm" : "inch",
      machine: getSection(0).getType() === TYPE_MILLING ? "mill" : "lathe"});
  });
}
function onSection() {
  nextGuard(function () {
    nextOperationLabel = nextLabel(currentSection, getCurrentSectionId());
    var issues = nextSectionIssues(currentSection);
    if (issues.length) { throw new Error("Next-NC: " + nextOperationLabel + ":\n  - " + issues.join("\n  - ")); }
    if ((currentSection.getType() === TYPE_MILLING) !== (nextProgram.machine === "mill")) { throw new Error("Next-NC: section machine type changed after precheck."); }
    setRotation(currentSection.workPlane);
    nextSetFeedMode(currentSection.feedMode);
    var mode = tool.getSpindleMode();
    var css = mode === SPINDLE_CONSTANT_SURFACE_SPEED;
    nextSpindle = {mode: css ? "css" : "rpm", speed: css ? tool.surfaceSpeed : Math.abs(spindleSpeed),
      clockwise: nextBoolean(tool.clockwise, "Fusion spindle direction"), maximumRPM: tool.maximumSpindleSpeed};
    nextSection = nextProgram.addSection({
      name: hasParameter("operation-comment") ? getParameter("operation-comment") : (nextProgram.machine === "mill" ? "Milling " : "Turning ") + (getCurrentSectionId() + 1),
      tool: {number: tool.number, offset: nextToolOffset(currentSection, tool), description: tool.comment || ""},
      workOffset: currentSection.workOffset,
      start: nextPoint(getFramePosition(currentSection.getInitialPosition())),
      spindle: nextSpindle, coolant: nextCoolant(tool.coolant)
    });
  });
}
function onRapid(x, y, z) { nextGuard(function () { nextNeedSection(); nextSection.rapid([x, y, z]); }); }
function onLinear(x, y, z, feed) {
  nextGuard(function () {
    nextNeedSection();
    var moved = nextSection.position[0] !== x || nextSection.position[1] !== y || nextSection.position[2] !== z;
    nextSection.linear([x, y, z], nextFeed(feed));
    if (nextCycle && moved) { ++nextCycleCuttingMoves; }
  });
}
function onCircular(clockwise, cx, cy, cz, x, y, z, feed) {
  nextGuard(function () {
    nextNeedSection();
    var milling = nextProgram.machine === "mill", plane = getCircularPlane();
    if ((!milling && (plane !== PLANE_ZX || isHelical())) || [PLANE_XY, PLANE_ZX, PLANE_YZ].indexOf(plane) < 0) {
      throw new Error("Next-NC: only planar XZ arcs for turning and principal-plane arcs for XYZ milling are supported.");
    }
    if (milling && isHelical()) {
      if (!canLinearize()) { throw new Error("Next-NC: Fusion cannot linearize this milling helix."); }
      var helixTolerance = nextArcTolerance();
      linearize(helixTolerance);
      nextFinishHelix(x, y, z, feed, helixTolerance);
      ++nextLinearizedArcs;
      nextLog("NEXTNC HELIX LINEARIZED " + JSON.stringify({operation: nextOperationLabel, tolerance: nextArcTolerance()}));
      return;
    }
    clockwise = nextBoolean(clockwise, "Fusion onCircular clockwise flag");
    var fullCircle = nextBoolean(isFullCircle(), "Fusion full-circle flag");
    try { nextSection.arc([x, y, z], [cx, cy, cz], clockwise, nextFeed(feed), fullCircle, plane === PLANE_XY ? "XY" : plane === PLANE_YZ ? "YZ" : "XZ"); }
    catch (e) {
      if (e.code !== "ARC_RADII" || fullCircle) { throw e; }
      var limit = nextArcTolerance(), remaining = limit - e.radialDifference;
      if (!(remaining > 0) || !canLinearize()) {
        throw new Error("Next-NC: arc endpoint radius difference " + e.radialDifference + " exceeds the available linearization budget " +
          limit + " or Fusion cannot linearize this record. Review/regenerate this operation; no arc geometry was changed.");
      }
      // The strict writer has not appended the rejected arc or advanced position.
      // Ask Fusion to generate the approximation; do not invent a new arc center.
      linearize(remaining);
      if (nextSection.position[0] !== x || nextSection.position[1] !== y || nextSection.position[2] !== z) {
        throw new Error("Next-NC: Fusion arc linearization did not reach the supplied endpoint; export stopped.");
      }
      ++nextLinearizedArcs;
      nextLog("NEXTNC ARC LINEARIZED " + JSON.stringify({operation: nextOperationLabel,
        record: getCurrentRecordId(), radialDifference: e.radialDifference, tolerance: remaining, units: unit === MM ? "mm" : "inch"}));
    }
  });
}
function onDwell(seconds) { nextGuard(function () { nextNeedSection(); nextSection.dwell(seconds); }); }
function onFeedMode(mode) { nextSetFeedMode(mode); }
function onSpindleSpeed(speed) {
  nextGuard(function () {
    nextNeedSection();
    if (nextSpindle.mode !== "rpm") { throw new Error("Next-NC: in-section CSS changes are unsupported; start a new operation."); }
    nextSpindle.speed = Math.abs(speed); nextSection.setSpindle(nextSpindle);
  });
}
function onRadiusCompensation() {
  if (radiusCompensation === RADIUS_COMPENSATION_OFF) { return; }
  var side = radiusCompensation === RADIUS_COMPENSATION_LEFT ? "left" :
    radiusCompensation === RADIUS_COMPENSATION_RIGHT ? "right" : "unrecognized mode " + radiusCompensation;
  var comp = nextCompensation(currentSection);
  var detail = !comp ? "Fusion did not supply Compensation Type metadata, so precheck could not detect this request. " :
    "Fusion reported Compensation Type = " + comp.name + ", but the motion requests controller-side compensation. " +
    "If the operation already shows In computer, regenerate it and check that you selected the regenerated operation. ";
  nextReject("[COMPENSATION] The toolpath requests " + side + " controller-side tool-nose compensation. " + detail + nextCompensationFix());
}
function onToolCompensation() { nextReject("Dual tool compensation changes are unsupported."); }
function onCycle() {
  nextNeedSection();
  if (nextCycle) { throw new Error("Next-NC: [CYCLE] Nested cycle before the previous cycle ended."); }
  var type = typeof cycleType === "string" ? cycleType : "unavailable";
  nextCycle = {type: type, points: 0};
  if (nextProgram.machine !== "mill" || nextSupportedCycles.indexOf(type) < 0) {
    nextReject("[CYCLE] Canned cycles are not emitted. Fusion expansion supports only fixed XYZ milling drilling, counter-boring, chip-breaking and deep-drilling; received " + nextDiagnosticText(type) + ". Threading, tapping, probing and spindle-stop/orientation cycles require a different supported process.");
  }
  var fields = ["clearance", "retract", "stock", "depth", "feedrate", "dwell", "incrementalDepth", "incrementalDepthReduction", "minimumIncrementalDepth", "accumulatedDepth", "chipBreakDistance"];
  nextCycle.parameters = {};
  for (var i = 0; i < fields.length; ++i) {
    if (cycle[fields[i]] !== undefined) { nextCycle.parameters[fields[i]] = cycle[fields[i]]; }
  }
  if (cycle.stopSpindle !== undefined && nextBoolean(cycle.stopSpindle, "cycle stopSpindle")) {
    throw new Error("Next-NC: [CYCLE] Spindle-stop drilling is not supported by this profile.");
  }
  if (typeof expandCyclePoint !== "function") { throw new Error("Next-NC: [CYCLE] This Fusion engine does not provide cycle expansion."); }
  if (nextCycleTypes.indexOf(type) < 0) { nextCycleTypes.push(type); }
}
function onCyclePoint(x, y, z) {
  nextNeedSection();
  if (!nextCycle || nextCycle.type !== cycleType) { throw new Error("Next-NC: [CYCLE] Missing or changed cycle identity during expansion."); }
  // Fusion owns depths, pecks, clearance and feed. Its expansion calls our normal
  // validated motion/dwell callbacks. Never substitute a hand-written cycle.
  var before = nextCycleCuttingMoves;
  expandCyclePoint(x, y, z);
  if (nextCycleCuttingMoves === before) { throw new Error("Next-NC: [CYCLE] Fusion expansion produced no cutting move for this cycle point. Review the cycle depth and regenerate the operation."); }
  ++nextCycle.points; ++nextExpandedCyclePoints;
}
function onCycleEnd() {
  if (!nextCycle) { throw new Error("Next-NC: [CYCLE] Cycle end without an accepted cycle."); }
  if (!nextCycle.points) { throw new Error("Next-NC: [CYCLE] Cycle contains no points."); }
  nextLog("NEXTNC CYCLE EXPANDED " + JSON.stringify({operation: nextOperationLabel, cycle: nextCycle, units: unit === MM ? "mm" : "inch"}));
  nextCycle = undefined;
}
function onCyclePath() { nextReject("Cycle paths are unsupported."); }
function onLinear5D() { nextReject("Multi-axis motion is unsupported."); }
function onRapid5D() { nextReject("Multi-axis motion is unsupported."); }
function onPassThrough() { nextReject("Pass-through NC is unsupported."); }
function onManualNC() { nextReject("Manual NC instructions are unsupported in this profile."); }
function onOrientateSpindle() { nextReject("Spindle orientation is unsupported."); }
function onMachineCommand() { nextReject("Machine-specific commands are unsupported."); }
function onSectionSpecialCycle() { nextReject("Special cycles are unsupported."); }
function onSpecialCycle() { nextReject("Special cycles are unsupported."); }
function onPower() { nextReject("Power-control instructions are unsupported."); }
function onLiveAlignment() { nextReject("Live part alignment is unsupported."); }
function onCommand(command) {
  if (nextCycle) { nextReject("[CYCLE] Fusion expansion requested unsupported command " + getCommandStringId(command) + ". Only resolved motion and dwell are supported for drilling cycles."); }
  if (command !== COMMAND_END) { nextReject("Unsupported command: " + getCommandStringId(command) + ". Set spindle and coolant in the Fusion operation."); }
}
function onSectionEnd() {
  if (nextCycle) { throw new Error("Next-NC: [CYCLE] Section ended before cycle expansion completed."); }
  nextSection = undefined; nextOperationLabel = "";
}
function onClose() {
  nextGuard(function () {
    // Nothing is emitted before the entire program has been accepted.
    if (nextCycle) { throw new Error("Next-NC: [CYCLE] Program ended before cycle expansion completed."); }
    var text = nextProgram.toSTEP();
    // The writer emits ASCII, so character count equals byte count here.
    if (text.length > 32 * 1024 * 1024) { throw new Error("Next-NC: Export exceeds the translator's 32 MiB input limit. Split the selected operations into separate programs and post again."); }
    var output = text.split("\n");
    for (var i = 0; i < output.length - 1; ++i) { writeln(output[i]); }
    nextLog("NEXTNC OUTPUT WRITTEN " + JSON.stringify({release: NextNC.version, callbacks: nextEventCount,
      sections: getNumberOfSections(), lines: output.length - 1, linearizedArcs: nextLinearizedArcs,
      expandedCyclePoints: nextExpandedCyclePoints, expandedCycleTypes: nextCycleTypes,
      summary: nextProgram.lastExport}));
  });
}

// Explicit entry-point wrapping also catches failures outside nextGuard.
onOpen = nextCallback("onOpen", onOpen);
onSection = nextCallback("onSection", onSection);
onRapid = nextCallback("onRapid", onRapid);
onLinear = nextCallback("onLinear", onLinear);
onCircular = nextCallback("onCircular", onCircular);
onDwell = nextCallback("onDwell", onDwell);
onFeedMode = nextCallback("onFeedMode", onFeedMode);
onSpindleSpeed = nextCallback("onSpindleSpeed", onSpindleSpeed);
onRadiusCompensation = nextCallback("onRadiusCompensation", onRadiusCompensation);
onToolCompensation = nextCallback("onToolCompensation", onToolCompensation);
onCycle = nextCallback("onCycle", onCycle);
onCyclePoint = nextCallback("onCyclePoint", onCyclePoint);
onCycleEnd = nextCallback("onCycleEnd", onCycleEnd);
onCyclePath = nextCallback("onCyclePath", onCyclePath);
onLinear5D = nextCallback("onLinear5D", onLinear5D);
onRapid5D = nextCallback("onRapid5D", onRapid5D);
onPassThrough = nextCallback("onPassThrough", onPassThrough);
onManualNC = nextCallback("onManualNC", onManualNC);
onOrientateSpindle = nextCallback("onOrientateSpindle", onOrientateSpindle);
onMachineCommand = nextCallback("onMachineCommand", onMachineCommand);
onSectionSpecialCycle = nextCallback("onSectionSpecialCycle", onSectionSpecialCycle);
onSpecialCycle = nextCallback("onSpecialCycle", onSpecialCycle);
onPower = nextCallback("onPower", onPower);
onLiveAlignment = nextCallback("onLiveAlignment", onLiveAlignment);
onCommand = nextCallback("onCommand", onCommand);
onSectionEnd = nextCallback("onSectionEnd", onSectionEnd);
onClose = nextCallback("onClose", onClose);
