// Generated by npm run build. Edit src/next-nc.js and src/fusion-adapter.js.
/* SPDX-License-Identifier: MIT
 * Original AP238 toolpath writer. ES5 syntax also runs inside Autodesk's post engine.
 */
var NextNC = (function () {
  "use strict";
  var VERSION = "0.1.2";
  var PROFILE = "next-nc/turning-toolpath/0.1";
  function requireValue(ok, message) { if (!ok) { throw new Error("Next-NC: " + message); } }
  function finite(n, label) {
    requireValue(typeof n === "number" && isFinite(n) && Math.abs(n) < 1e15, label + " must be a finite number below 1e15 in magnitude");
    return n;
  }
  function positive(n, label) { finite(n, label); requireValue(n > 0, label + " must be positive"); return n; }
  function integer(n, label, minimum) {
    finite(n, label); requireValue(n === Math.floor(n) && n >= minimum, label + " must be an integer >= " + minimum); return n;
  }
  function point(p) {
    requireValue(p && p.length === 3, "a point must have X, Y, Z coordinates");
    var q = [finite(p[0], "X"), finite(p[1], "Y"), finite(p[2], "Z")];
    requireValue(Math.abs(q[1]) <= 1e-9, "only XZ turning with Y=0 is supported"); q[1] = 0; return q;
  }
  function same(a, b) { return a[0] === b[0] && a[1] === b[1] && a[2] === b[2]; }
  function distance(a, b) { return Math.sqrt(Math.pow(a[0] - b[0], 2) + Math.pow(a[2] - b[2], 2)); }
  function copySpindle(s) {
    requireValue(s && (s.mode === "rpm" || s.mode === "css"), "spindle mode must be rpm or css");
    requireValue(typeof s.clockwise === "boolean", "spindle direction must be explicit");
    var result = {mode: s.mode, speed: positive(s.speed, "spindle speed"), clockwise: s.clockwise};
    if (s.mode === "css") { result.maximumRPM = positive(s.maximumRPM, "CSS maximum RPM"); }
    return result;
  }
  function coolant(c) { requireValue(["off", "flood", "mist", "through tool"].indexOf(c) >= 0, "unsupported coolant: " + c); return c; }
  function feed(f) {
    requireValue(f && (f.mode === "perMinute" || f.mode === "perRevolution"), "feed mode must be perMinute or perRevolution");
    return {value: positive(f.value, "feed"), mode: f.mode};
  }
  function stateKey(s, f) {
    return [s.mode, s.speed, s.maximumRPM || 0, s.clockwise, f ? f.mode : "", f ? f.value : ""].join("|");
  }
  function Section(spec) {
    requireValue(spec && spec.tool, "section and tool are required");
    this.name = String(spec.name || "Turning");
    this.tool = {number: integer(spec.tool.number, "tool number", 1),
      offset: integer(spec.tool.offset, "tool offset", 0), description: String(spec.tool.description || "")};
    this.workOffset = integer(spec.workOffset, "Fusion work offset", 0);
    this.start = point(spec.start);
    this.position = this.start.slice();
    this.spindle = copySpindle(spec.spindle);
    this.coolant = coolant(spec.coolant);
    this.initialSpindle = copySpindle(spec.spindle);
    this.initialCoolant = this.coolant;
    this.paths = [];
  }
  Section.prototype.setSpindle = function (s) { this.spindle = copySpindle(s); };
  Section.prototype.setCoolant = function (c) { this.coolant = coolant(c); };
  Section.prototype.append = function (path, f) {
    path.spindle = copySpindle(this.spindle); path.coolant = this.coolant;
    path.feed = f ? feed(f) : null;
    path.key = path.kind + "|" + path.coolant + "|" + stateKey(path.spindle, path.feed);
    var previous = this.paths[this.paths.length - 1];
    // Compact only consecutive linear moves with identical process state.
    // Every intermediate vertex is preserved; this is not geometric smoothing.
    if ((path.kind === "rapid" || path.kind === "linear") && previous && previous.key === path.key) {
      previous.points.push(path.points[1]);
    } else { this.paths.push(path); }
  };
  Section.prototype.rapid = function (end) {
    end = point(end);
    if (!same(this.position, end)) { this.append({kind: "rapid", points: [this.position, end]}); }
    this.position = end;
  };
  Section.prototype.linear = function (end, f) {
    end = point(end); f = feed(f);
    if (!same(this.position, end)) { this.append({kind: "linear", points: [this.position, end]}, f); }
    this.position = end;
  };
  Section.prototype.arc = function (end, center, clockwise, f, fullCircle) {
    end = point(end); center = point(center); f = feed(f);
    requireValue(typeof clockwise === "boolean", "arc direction must be explicit");
    var radius = positive(distance(this.position, center), "arc radius");
    requireValue(Math.abs(distance(end, center) - radius) <= Math.max(1e-7, radius * 1e-6), "arc endpoints have different radii");
    requireValue(fullCircle ? same(this.position, end) : !same(this.position, end), "full-circle flag must match arc endpoints");
    this.append({kind: "arc", start: this.position, end: end, center: center, radius: radius,
      clockwise: clockwise, fullCircle: !!fullCircle}, f);
    this.position = end;
  };
  Section.prototype.dwell = function (seconds) { this.append({kind: "dwell", seconds: positive(seconds, "dwell")}); };
  function Program(options) {
    options = options || {};
    requireValue(options.units === "mm" || options.units === "inch", "units must be mm or inch");
    this.units = options.units; this.name = String(options.name || "Next-NC program");
    this.timestamp = options.timestamp || new Date().toISOString();
    requireValue(/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z$/.test(this.timestamp), "timestamp must be UTC ISO 8601");
    this.sections = [];
  }
  Program.prototype.addSection = function (spec) { var s = new Section(spec); this.sections.push(s); return s; };
  function real(n) {
    finite(n, "STEP real");
    var result = (n === 0 ? "0" : String(n)).toUpperCase();
    if (result.indexOf("E") >= 0) {
      var parts = result.split("E"); if (parts[0].indexOf(".") < 0) { parts[0] += "."; }
      return parts[0] + "E" + parts[1];
    }
    return result.indexOf(".") >= 0 ? result : result + ".";
  }
  function str(value) {
    var s = String(value), result = "'", hex, code, i;
    for (i = 0; i < s.length; ++i) {
      code = s.charCodeAt(i);
      if (s[i] === "'") { result += "''"; }
      else if (s[i] === "\\") { result += "\\\\"; }
      else if (code >= 32 && code <= 126) { result += s[i]; }
      else {
        // Part 21 X2 encodes UTF-16 code units, including surrogate pairs.
        hex = code.toString(16).toUpperCase();
        if (code >= 0xD800 && code <= 0xDBFF) {
          var low = s.charCodeAt(++i);
          requireValue(low >= 0xDC00 && low <= 0xDFFF, "unpaired Unicode surrogate");
          hex += ("0000" + low.toString(16).toUpperCase()).slice(-4);
        } else { requireValue(code < 0xDC00 || code > 0xDFFF, "unpaired Unicode surrogate"); }
        result += "\\X2\\" + (hex.length < 4 ? ("0000" + hex).slice(-4) : hex) + "\\X0\\";
      }
    }
    return result + "'";
  }
  function list(items) { return "(" + items.join(",") + ")"; }
  function Writer() { this.lines = []; }
  Writer.prototype.raw = function (value) { this.lines.push(value); return "#" + this.lines.length; };
  Writer.prototype.add = function (type, args) { return this.raw(type + list(args)); };
  Writer.prototype.textItem = function (name, value) { return this.add("DESCRIPTIVE_REPRESENTATION_ITEM", [str(name), str(value)]); };
  Writer.prototype.point = function (p) { return this.add("CARTESIAN_POINT", ["''", list(p.map(real))]); };
  Writer.prototype.rep = function (type, name, items, context) { return this.add(type || "REPRESENTATION", [str(name), list(items), context || this.unitless]); };
  Writer.prototype.property = function (target, name, rep) {
    var prop = this.add("ACTION_PROPERTY", [str(name), "''", target]);
    this.add("ACTION_PROPERTY_REPRESENTATION", ["''", "''", prop, rep]);
  };
  Writer.prototype.textProperty = function (target, name, value) {
    this.property(target, name, this.rep(null, "", [this.textItem(name, value)]));
  };
  Writer.prototype.measure = function (name, value, unit) {
    return this.add("MEASURE_REPRESENTATION_ITEM", [str(name), "NUMERIC_MEASURE(" + real(value) + ")", unit]);
  };
  Writer.prototype.rel = function (kind, a, b, order) {
    var args = ["''", "''", a, b]; if (order !== undefined) { args.push(real(order)); }
    return this.add(kind, args);
  };
  Writer.prototype.method = function (type, name, description) { return this.add(type, [str(name), str(description || ""), "''", "''"]); };
  Writer.prototype.units = function (units) {
    this.unitless = this.add("REPRESENTATION_CONTEXT", ["''", str("units not necessary")]);
    this.length = this.raw("(LENGTH_UNIT() NAMED_UNIT(*) SI_UNIT(.MILLI.,.METRE.))");
    if (units === "inch") {
      var factor = this.add("LENGTH_MEASURE_WITH_UNIT", ["LENGTH_MEASURE(25.4)", this.length]);
      var dims = this.add("DIMENSIONAL_EXPONENTS", ["1.", "0.", "0.", "0.", "0.", "0.", "0."]);
      this.length = this.raw("(CONVERSION_BASED_UNIT('inch'," + factor + ") LENGTH_UNIT() NAMED_UNIT(" + dims + "))");
    }
    var angle = this.raw("(NAMED_UNIT(*) PLANE_ANGLE_UNIT() SI_UNIT($,.RADIAN.))");
    var solid = this.raw("(NAMED_UNIT(*) SI_UNIT($,.STERADIAN.) SOLID_ANGLE_UNIT())");
    this.context = this.raw("(GEOMETRIC_REPRESENTATION_CONTEXT(3) GLOBAL_UNIT_ASSIGNED_CONTEXT(" + list([this.length, angle, solid]) + ") REPRESENTATION_CONTEXT('','3D'))");
    this.second = this.raw("(NAMED_UNIT(*) SI_UNIT($,.SECOND.) TIME_UNIT())");
    var minuteFactor = this.add("TIME_MEASURE_WITH_UNIT", ["TIME_MEASURE(60.)", this.second]);
    var timeDims = this.add("DIMENSIONAL_EXPONENTS", ["0.", "0.", "1.", "0.", "0.", "0.", "0."]);
    var minute = this.raw("(CONVERSION_BASED_UNIT('minute'," + minuteFactor + ") NAMED_UNIT(" + timeDims + ") TIME_UNIT())");
    var zeroDims = this.add("DIMENSIONAL_EXPONENTS", ["0.", "0.", "0.", "0.", "0.", "0.", "0."]);
    var rev = this.add("CONTEXT_DEPENDENT_UNIT", [zeroDims, str("revolution")]);
    var self = this;
    function divided(a, b) {
      return self.add("DERIVED_UNIT", [list([self.add("DERIVED_UNIT_ELEMENT", [a, "1."]), self.add("DERIVED_UNIT_ELEMENT", [b, "-1."])])]);
    }
    this.rpm = divided(rev, minute); this.perMinute = divided(this.length, minute); this.perRevolution = divided(this.length, rev);
    this.technologyCache = {}; this.functionsCache = {};
  };
  Writer.prototype.technology = function (spindle, f) {
    var key = stateKey(spindle, f), cached = this.technologyCache[key]; if (cached) { return cached; }
    var tech = this.method("MACHINING_TECHNOLOGY", "", "turning"), items;
    // AP238 uses a right-handed sign: clockwise is negative (opposite Fusion).
    var signed = spindle.speed * (spindle.clockwise ? -1 : 1);
    if (spindle.mode === "css") {
      items = [this.measure("surface speed", signed, this.perMinute), this.measure("maximum rotational speed", spindle.maximumRPM, this.rpm)];
    } else { items = [this.measure("rotational speed", signed, this.rpm)]; }
    this.property(tech, "spindle", this.rep("MACHINING_SPINDLE_SPEED_REPRESENTATION", spindle.mode === "css" ? "cutting speed" : "spindle speed", items));
    if (f) {
      var name = f.mode === "perMinute" ? "feed speed" : "feed per revolution";
      this.property(tech, "feedrate", this.rep("MACHINING_FEED_SPEED_REPRESENTATION", name, [this.measure(name, f.value, this[f.mode])]));
    }
    this.textProperty(tech, "feedrate reference", "tool center point");
    this.technologyCache[key] = tech; return tech;
  };
  Writer.prototype.functions = function (coolantMode) {
    var cached = this.functionsCache[coolantMode]; if (cached) { return cached; }
    var functions = this.method("MACHINING_FUNCTIONS", "", "turning");
    this.textProperty(functions, "coolant", coolantMode === "off" ? "coolant off" : "coolant on");
    if (coolantMode !== "off") { this.textProperty(functions, "coolant type", coolantMode); }
    this.functionsCache[coolantMode] = functions; return functions;
  };
  Writer.prototype.curve = function (path) {
    if (path.kind !== "arc") { return this.add("POLYLINE", ["''", list(path.points.map(this.point.bind(this)))]); }
    var normal = this.add("DIRECTION", ["''", "(0.,1.,0.)"]);
    var direction = [(path.start[0] - path.center[0]) / path.radius, 0, (path.start[2] - path.center[2]) / path.radius];
    var ref = this.add("DIRECTION", ["''", list(direction.map(real))]);
    var placement = this.add("AXIS2_PLACEMENT_3D", ["''", this.point(path.center), normal, ref]);
    var circle = this.add("CIRCLE", ["''", placement, real(path.radius)]);
    // +Y is the G18/ZX plane normal; counterclockwise is right-handed about +Y.
    var first = path.fullCircle ? "(PARAMETER_VALUE(0.))" : list([this.point(path.start)]);
    var last = path.fullCircle ? "(PARAMETER_VALUE(" + real(2 * Math.PI) + "))" : list([this.point(path.end)]);
    return this.add("TRIMMED_CURVE", ["''", circle, first, last, path.clockwise ? ".F." : ".T.", path.fullCircle ? ".PARAMETER." : ".CARTESIAN."]);
  };
  Writer.prototype.toolpath = function (operation, path, index) {
    var tp = this.method("MACHINING_TOOLPATH", "Path " + index, path.kind === "dwell" ? "feedstop" : "cutter location trajectory");
    this.rel("MACHINING_TOOLPATH_SEQUENCE_RELATIONSHIP", operation, tp, index);
    this.rel("MACHINING_TECHNOLOGY_RELATIONSHIP", tp, this.technology(path.spindle, path.feed));
    this.rel("MACHINING_FUNCTIONS_RELATIONSHIP", tp, this.functions(path.coolant));
    this.textProperty(tp, "priority", "required");
    if (path.kind === "dwell") {
      var time = this.add("MEASURE_REPRESENTATION_ITEM", [str("dwell"), "TIME_MEASURE(" + real(path.seconds) + ")", this.second]);
      this.property(tp, "dwell", this.rep(null, "", [time]));
    } else {
      this.textProperty(tp, "trajectory type", "trajectory path"); this.textProperty(tp, "direction", "beginning to end");
      this.property(tp, "basic curve", this.rep(null, "", [this.curve(path)], this.context));
      if (path.kind === "rapid") {
        this.property(tp, "speed profile", this.rep("MACHINING_TOOLPATH_SPEED_PROFILE_REPRESENTATION", "", [this.textItem("", "rapid")]));
      }
    }
  };
  Writer.prototype.project = function (program) {
    var app = this.add("APPLICATION_CONTEXT", [str("Application protocol for the exchange of CNC data")]);
    this.add("APPLICATION_PROTOCOL_DEFINITION", [str("international standard"), str("integrated_cnc_schema"), "2007", app]);
    var context = this.add("PRODUCT_CONTEXT", [str("CNC Machining"), app, str("manufacturing")]);
    var defContext = this.add("PRODUCT_DEFINITION_CONTEXT", [str("CNC Machining"), app, str("manufacturing")]);
    var project = this.add("MACHINING_PROJECT", [str(program.name), str(program.name), "$", list([context])]);
    var formation = this.add("PRODUCT_DEFINITION_FORMATION", [str(VERSION), "''", project]);
    var projectDef = this.add("PRODUCT_DEFINITION", ["''", "''", formation, defContext]);
    var workplan = this.method("MACHINING_WORKPLAN", program.name, "");
    var process = this.add("PRODUCT_DEFINITION_PROCESS", [str("machining"), "''", workplan, "''"]);
    this.add("PROCESS_PRODUCT_ASSOCIATION", ["''", "''", projectDef, process]);
    this.textProperty(workplan, "next-nc profile", PROFILE);
    this.textProperty(workplan, "next-nc coordinates", "WCS; X radius; Y zero; Z axial; Fusion tool reference point");
    var part = this.add("PRODUCT", [str("workpiece"), str("Toolpath-only workpiece; geometry not supplied"), "$", list([context])]);
    var partFormation = this.add("PRODUCT_DEFINITION_FORMATION", ["''", "''", part]);
    var partDef = this.add("PRODUCT_DEFINITION", [str("workpiece"), "''", partFormation, defContext]);
    this.add("MACHINING_PROJECT_WORKPIECE_RELATIONSHIP", ["''", str("workpiece"), "''", projectDef, partDef]);
    this.partShape = this.add("PRODUCT_DEFINITION_SHAPE", ["''", "''", partDef]);
    return workplan;
  };
  Writer.prototype.section = function (workplan, section, index) {
    requireValue(section.paths.length > 0, "section '" + section.name + "' contains no motion or dwell");
    var ws = this.method("MACHINING_WORKINGSTEP", section.name, "machining");
    this.rel("MACHINING_PROCESS_SEQUENCE_RELATIONSHIP", workplan, ws, index);
    var operation = this.method("TURNING_TYPE_OPERATION", section.name, "");
    this.rel("MACHINING_OPERATION_RELATIONSHIP", ws, operation);
    // A generic CC1 toolpath feature avoids claiming feature-based turning geometry.
    var feature = this.add("INSTANCED_FEATURE", ["''", str("toolpath"), "''", str("toolpath"), this.partShape, ".T."]);
    var featureProcess = this.method("MACHINING_FEATURE_PROCESS", "", "machining");
    var process = this.add("PROPERTY_PROCESS", [str("machining"), "''", featureProcess, "''"]);
    this.add("PROCESS_PROPERTY_ASSOCIATION", ["''", str("machining"), process, feature]);
    this.rel("MACHINING_FEATURE_RELATIONSHIP", ws, featureProcess);
    // Logical tool reference, not an invented ISO turning-tool body/holder model.
    var toolType = this.add("ACTION_RESOURCE_TYPE", [str("cutting tool")]);
    this.add("MACHINING_TOOL", [str(section.tool.number), str(section.tool.description), list([operation]), toolType]);
    this.textProperty(operation, "next-nc tool offset", String(section.tool.offset));
    this.textProperty(operation, "next-nc work offset", String(section.workOffset));
    this.property(operation, "next-nc entry point", this.rep(null, "", [this.point(section.start)], this.context));
    this.rel("MACHINING_TECHNOLOGY_RELATIONSHIP", operation, this.technology(section.initialSpindle, null));
    this.rel("MACHINING_FUNCTIONS_RELATIONSHIP", operation, this.functions(section.initialCoolant));
    for (var i = 0; i < section.paths.length; ++i) { this.toolpath(operation, section.paths[i], i + 1); }
  };
  Program.prototype.toSTEP = function () {
    requireValue(this.sections.length > 0, "program contains no sections");
    var w = new Writer(); w.units(this.units); var workplan = w.project(this);
    for (var i = 0; i < this.sections.length; ++i) { w.section(workplan, this.sections[i], i + 1); }
    var lines = ["ISO-10303-21;", "HEADER;",
      "FILE_DESCRIPTION((" + str("Experimental AP238 toolpath; " + PROFILE) + "),'2;1');",
      "FILE_NAME(" + str(this.name + ".stpnc") + "," + str(this.timestamp) + ",(''),('')," + str("Fusion360Next-NC " + VERSION) + ",'Fusion360Next-NC','');",
      "FILE_SCHEMA(('INTEGRATED_CNC_SCHEMA'));", "ENDSEC;", "DATA;"];
    for (i = 0; i < w.lines.length; ++i) { lines.push("#" + (i + 1) + "=" + w.lines[i] + ";"); }
    lines.push("ENDSEC;", "END-ISO-10303-21;"); return lines.join("\n") + "\n";
  };
  return {Program: Program, version: VERSION, profile: PROFILE, stepString: str, stepReal: real};
}());
if (typeof module !== "undefined" && module.exports) { module.exports = NextNC; }

/* SPDX-License-Identifier: MIT
 * Fusion callbacks. Bundled after next-nc.js to produce a standalone CPS.
 */
description = "Next-NC - experimental AP238 XZ turning";
vendor = "Fusion360Next-NC";
vendorUrl = "https://github.com/markmounteer/Fusion360Next-NC";
legal = "Copyright (c) 2026 Mark Mounteer. MIT License.";
// Autodesk's configuration format version, NOT the Next-NC release number.
version = "1.0";
certificationLevel = 0;
minimumRevision = 45917;
extension = "stpnc";
longDescription = "Next-NC " + NextNC.version + ". Experimental toolpath-level STEP-NC/AP238 exporter for single-spindle XZ turning. Requires a Next-NC-aware consumer; LinuxCNC cannot load this file directly. No controller or machine options are duplicated here.";
capabilities = CAPABILITY_TURNING;
setCodePage("ascii");
properties = {};
tolerance = spatial(0.002, MM);
minimumChordLength = spatial(0.001, MM);
minimumCircularRadius = spatial(0.001, MM);
maximumCircularRadius = spatial(100000, MM);
minimumCircularSweep = toRad(0.001);
maximumCircularSweep = 2 * Math.PI;
allowHelicalMoves = false;
allowSpiralMoves = false;
allowedCircularPlanes = 1 << PLANE_ZX;

var nextProgram;
var nextSection;
var nextFeedMode;
var nextSpindle;
var nextFailed = false;
var nextOperationLabel = "";
var nextRecentEvents = [];
var nextEventCount = 0;
var nextStartedUTC = "";
var nextSectionDiagnostics = [];

// Use the engine log: direct file access is restricted by Fusion's security
// level, and no callback can run when the engine rejects the global script.
function nextRead(read) {
  try { var value = read(); return value === undefined ? "unavailable" : value; }
  catch (e) { return "unavailable: " + String(e.message || e); }
}
function nextLog(message) {
  // Logging must never replace the original error or change export acceptance.
  try { log(message); } catch (e) { /* The engine still receives error(). */ }
}
function nextContext() {
  return {
    schema: "next-nc/diagnostic/1", release: NextNC.version, profile: NextNC.profile,
    configurationVersion: version, minimumRevision: minimumRevision, certificationLevel: certificationLevel,
    engine: nextRead(function () { return getVersion(); }),
    securityLevel: nextRead(function () { return getSecurityLevel(); }),
    configurationPath: nextRead(function () { return getConfigurationPath(); }),
    outputPath: nextRead(function () { return getOutputPath(); }),
    program: nextRead(function () { return programName; }), units: unit === MM ? "mm" : "inch",
    startedUTC: nextStartedUTC, sectionCount: nextRead(function () { return getNumberOfSections(); })
  };
}
function nextSnapshot(section, index, issues) {
  return nextRead(function () {
    var t = section.getTool(), comp = nextCompensation(section);
    return {label: nextLabel(section, index), section: index + 1, type: section.getType(),
      tool: t.number, toolOffset: t.compensationOffset, workOffset: section.workOffset,
      compensation: comp || "metadata missing; runtime guard active", feedMode: section.feedMode,
      spindleMode: t.getSpindleMode(), surfaceSpeed: t.surfaceSpeed, maximumRPM: t.maximumSpindleSpeed,
      clockwise: t.clockwise, coolant: t.coolant,
      workPlane: {forward: nextPoint(section.workPlane.forward), right: nextPoint(section.workPlane.right)},
      issues: issues};
  });
}
function nextFail(e) {
  if (nextFailed) { error("Next-NC: export has already failed; see the first diagnostic."); return; }
  nextFailed = true;
  var message = String(e.message || e);
  try {
    var report = nextContext();
    report.status = "failed";
    report.failedUTC = new Date().toISOString();
    report.error = message;
    report.callback = nextRecentEvents.length ? nextRecentEvents[nextRecentEvents.length - 1].callback : "unknown";
    report.operation = nextOperationLabel || "No active operation (see section diagnostics)";
    report.record = nextRead(function () { return getCurrentRecordId(); });
    report.ncLocation = nextRead(function () { return getCurrentNCLocation(); });
    report.spindle = nextSpindle;
    report.feedMode = nextFeedMode;
    report.stack = e.stack || "not supplied by engine";
    report.callbackCount = nextEventCount;
    report.recentEvents = nextRecentEvents;
    report.sections = nextSectionDiagnostics;
    report.sectionSnapshotLimit = 200;
    report.outputStatus = "FAILED. Do not use the output; serialization/output may be incomplete.";
    nextLog("NEXTNC DIAGNOSTIC BEGIN\n" + JSON.stringify(report, null, 2) + "\nNEXTNC DIAGNOSTIC END");
  } catch (reportError) {
    nextLog("Next-NC diagnostic assembly failed: " + String(reportError.message || reportError) + "; original error: " + message);
  }
  error(message + "\n\nNext-NC " + NextNC.version + ": see the detailed report in Fusion's full post log. " +
    "With the Windows collector installed, reports are archived at %LOCALAPPDATA%\\Fusion360Next-NC\\diagnostics\\latest-error.txt.");
}
function nextCallback(name, callback) {
  return function () {
    if (nextFailed) { error("Next-NC: export has already failed; see the first diagnostic."); return; }
    ++nextEventCount;
    nextRecentEvents.push({callback: name, arguments: Array.prototype.slice.call(arguments),
      record: nextRead(function () { return getCurrentRecordId(); })});
    if (nextRecentEvents.length > 12) { nextRecentEvents.shift(); }
    try { return callback.apply(this, arguments); }
    catch (e) { if (nextFailed) { throw e; } nextFail(e); }
  };
}

function nextDiagnosticText(value) { return String(value).replace(/[\x00-\x1f\x7f]/g, " ").replace(/"/g, "'"); }
function nextLabel(section, index) {
  var name = section.hasParameter("operation-comment") ? section.getParameter("operation-comment") : "";
  var sectionTool = section.getTool();
  return "Operation \"" + nextDiagnosticText(name || "Unnamed operation") + "\" (section " + (index + 1) +
    ", tool T" + nextDiagnosticText(sectionTool.number) + ")";
}
function nextCompensation(section) {
  // Missing metadata is not evidence of In computer. Keep the runtime guard active.
  if (!section.hasParameter("operation:compensationType")) { return null; }
  var value = section.getParameter("operation:compensationType");
  var names = {computer: "In computer", control: "In control", wear: "Wear", inverseWear: "Inverse wear", off: "Off"};
  var known = Object.prototype.hasOwnProperty.call(names, value);
  return {value: value, known: known, name: known ? names[value] : "unrecognized value \"" + nextDiagnosticText(value) + "\""};
}
function nextCompensationFix() {
  return "In Fusion, edit this operation > Passes > Compensation Type > In computer, regenerate its toolpath, then post again. " +
    "Do not select Off just to bypass this check; Off removes compensation.";
}
function nextPositive(value) { return typeof value === "number" && isFinite(value) && value > 0 && value < 1e15; }
function nextSectionIssues(section) {
  var issues = [];
  if (section.getType() !== TYPE_TURNING || section.isMultiAxis()) {
    issues.push("[SECTION] Only fixed XZ turning is supported. Select fixed turning operations for this post.");
  }
  if (section.isOptional()) { issues.push("[OPTIONAL] Optional sections are unsupported. Make this operation non-optional or exclude it."); }
  if (section.spindle !== SPINDLE_PRIMARY) { issues.push("[SPINDLE] Secondary-spindle operations are unsupported. Use a primary-spindle setup."); }
  var wp = section.workPlane;
  if (!isSameDirection(wp.forward, new Vector(0, 0, 1)) || !isSameDirection(wp.right, new Vector(1, 0, 0))) {
    issues.push("[WORKPLANE] Rotated/mirrored work planes are unsupported. Use an unrotated turning work plane (+X right, +Z forward).");
  }
  var comp = nextCompensation(section);
  if (comp && comp.value !== "computer" && comp.value !== "off") {
    issues.push("[COMPENSATION] Compensation Type is " + comp.name + ". " +
      (comp.known ? "This requests controller-side compensation, which this post does not support. " : "This post cannot interpret that setting. ") +
      nextCompensationFix());
  }
  if (section.hasAnyCycle()) {
    issues.push("[CYCLE] This section contains a cycle. Canned cycles and synchronized threading/tapping are unsupported; exclude it or use a post that supports it.");
  }
  if (section.feedMode !== FEED_PER_MINUTE && section.feedMode !== FEED_PER_REVOLUTION) {
    issues.push("[FEED] Unsupported feed mode. Use feed per minute or feed per revolution.");
  }
  var sectionTool = section.getTool(), mode = sectionTool.getSpindleMode();
  if (mode === SPINDLE_CONSTANT_SURFACE_SPEED) {
    if (!nextPositive(sectionTool.surfaceSpeed)) { issues.push("[CSS_SPEED] Set a positive surface speed in the Fusion operation's Tool tab."); }
    if (!nextPositive(sectionTool.maximumSpindleSpeed)) { issues.push("[CSS_LIMIT] Set a positive maximum spindle speed for CSS in the Fusion operation's Tool tab."); }
  } else if (mode !== SPINDLE_CONSTANT_SPINDLE_SPEED) {
    issues.push("[SPINDLE_MODE] Only constant RPM or constant surface speed is supported. Review the Fusion operation's spindle settings.");
  }
  if ([COOLANT_OFF, COOLANT_FLOOD, COOLANT_MIST, COOLANT_THROUGH_TOOL].indexOf(sectionTool.coolant) < 0) {
    issues.push("[COOLANT] Unsupported coolant selection. Supported modes are Off, Flood, Mist, and Through tool.");
  }
  return issues;
}
function nextPrecheck() {
  var problems = [], affected = 0, count = getNumberOfSections();
  if (!count) { throw new Error("Next-NC precheck: no machining sections selected. Select a turning operation and post again."); }
  for (var i = 0; i < count; ++i) {
    var section = getSection(i), issues = nextSectionIssues(section);
    if (nextSectionDiagnostics.length < 200) { nextSectionDiagnostics.push(nextSnapshot(section, i, issues)); }
    if (issues.length) {
      ++affected;
      problems.push(nextLabel(section, i) + ":\n  - " + issues.join("\n  - "));
    }
  }
  if (problems.length) {
    throw new Error("Next-NC " + NextNC.version + " precheck failed: " + affected + " of " + count + " section(s) need attention.\n\n" +
      problems.join("\n\n") + "\n\nNo STEP-NC program was written. Correct the listed settings and regenerate the affected toolpaths.");
  }
}

function nextGuard(fn) {
  if (nextFailed) { error("Next-NC: export has already failed."); return; }
  try { return fn(); } catch (e) { if (nextFailed) { throw e; } nextFail(e); }
}
function nextReject(message) {
  nextFail(new Error("Next-NC: " + (nextOperationLabel ? nextOperationLabel + ": " : "") + message));
}
function nextPoint(p) { return [p.x, p.y, p.z]; }
function nextFeed(value) { return {value: value, mode: nextFeedMode}; }
function nextSetFeedMode(mode) {
  if (mode === FEED_PER_MINUTE) { nextFeedMode = "perMinute"; }
  else if (mode === FEED_PER_REVOLUTION) { nextFeedMode = "perRevolution"; }
  else { nextReject("Inverse-time and unrecognized feed modes are unsupported."); }
}
function nextCoolant(mode) {
  if (mode === COOLANT_OFF) { return "off"; }
  if (mode === COOLANT_FLOOD) { return "flood"; }
  if (mode === COOLANT_MIST) { return "mist"; }
  if (mode === COOLANT_THROUGH_TOOL) { return "through tool"; }
  throw new Error("Next-NC: unsupported coolant mode " + mode);
}
function nextNeedSection() { if (!nextSection) { throw new Error("Next-NC: event outside a machining section"); } }
function onOpen() {
  nextGuard(function () {
    nextStartedUTC = new Date().toISOString();
    nextLog("NEXTNC START " + JSON.stringify(nextContext()));
    nextPrecheck();
    nextProgram = new NextNC.Program({name: programName || "Fusion turning", units: unit === MM ? "mm" : "inch"});
  });
}
function onSection() {
  nextGuard(function () {
    nextOperationLabel = nextLabel(currentSection, getCurrentSectionId());
    var issues = nextSectionIssues(currentSection);
    if (issues.length) { throw new Error("Next-NC: " + nextOperationLabel + ":\n  - " + issues.join("\n  - ")); }
    setRotation(currentSection.workPlane);
    nextSetFeedMode(currentSection.feedMode);
    var mode = tool.getSpindleMode();
    var css = mode === SPINDLE_CONSTANT_SURFACE_SPEED;
    nextSpindle = {mode: css ? "css" : "rpm", speed: css ? tool.surfaceSpeed : Math.abs(spindleSpeed),
      clockwise: tool.clockwise, maximumRPM: tool.maximumSpindleSpeed};
    nextSection = nextProgram.addSection({
      name: hasParameter("operation-comment") ? getParameter("operation-comment") : "Turning " + (getCurrentSectionId() + 1),
      tool: {number: tool.number, offset: tool.compensationOffset, description: tool.comment || ""},
      workOffset: currentSection.workOffset,
      start: nextPoint(getFramePosition(currentSection.getInitialPosition())),
      spindle: nextSpindle, coolant: nextCoolant(tool.coolant)
    });
  });
}
function onRapid(x, y, z) { nextGuard(function () { nextNeedSection(); nextSection.rapid([x, y, z]); }); }
function onLinear(x, y, z, feed) { nextGuard(function () { nextNeedSection(); nextSection.linear([x, y, z], nextFeed(feed)); }); }
function onCircular(clockwise, cx, cy, cz, x, y, z, feed) {
  nextGuard(function () {
    nextNeedSection();
    if (getCircularPlane() !== PLANE_ZX || isHelical()) { throw new Error("Next-NC: only planar XZ arcs are supported."); }
    nextSection.arc([x, y, z], [cx, cy, cz], clockwise, nextFeed(feed), isFullCircle());
  });
}
function onDwell(seconds) { nextGuard(function () { nextNeedSection(); nextSection.dwell(seconds); }); }
function onFeedMode(mode) { nextSetFeedMode(mode); }
function onSpindleSpeed(speed) {
  nextGuard(function () {
    nextNeedSection();
    if (nextSpindle.mode !== "rpm") { throw new Error("Next-NC: in-section CSS changes are unsupported; start a new operation."); }
    nextSpindle.speed = Math.abs(speed); nextSection.setSpindle(nextSpindle);
  });
}
function onRadiusCompensation() {
  if (radiusCompensation === RADIUS_COMPENSATION_OFF) { return; }
  var side = radiusCompensation === RADIUS_COMPENSATION_LEFT ? "left" :
    radiusCompensation === RADIUS_COMPENSATION_RIGHT ? "right" : "unrecognized mode " + radiusCompensation;
  var comp = nextCompensation(currentSection);
  var detail = !comp ? "Fusion did not supply Compensation Type metadata, so precheck could not detect this request. " :
    "Fusion reported Compensation Type = " + comp.name + ", but the motion requests controller-side compensation. " +
    "If the operation already shows In computer, regenerate it and check that you selected the regenerated operation. ";
  nextReject("[COMPENSATION] The toolpath requests " + side + " controller-side tool-nose compensation. " + detail + nextCompensationFix());
}
function onToolCompensation() { nextReject("Dual tool compensation changes are unsupported."); }
function onCycle() { nextReject("Canned cycles and spindle-synchronized threading are not implemented."); }
function onCyclePoint() { nextReject("Cycle motion is unsupported."); }
function onCyclePath() { nextReject("Cycle paths are unsupported."); }
function onLinear5D() { nextReject("Multi-axis motion is unsupported."); }
function onRapid5D() { nextReject("Multi-axis motion is unsupported."); }
function onPassThrough() { nextReject("Pass-through NC is unsupported."); }
function onManualNC() { nextReject("Manual NC instructions are unsupported in this profile."); }
function onOrientateSpindle() { nextReject("Spindle orientation is unsupported."); }
function onMachineCommand() { nextReject("Machine-specific commands are unsupported."); }
function onSectionSpecialCycle() { nextReject("Special cycles are unsupported."); }
function onSpecialCycle() { nextReject("Special cycles are unsupported."); }
function onPower() { nextReject("Power-control instructions are unsupported."); }
function onLiveAlignment() { nextReject("Live part alignment is unsupported."); }
function onCommand(command) {
  if (command !== COMMAND_END) { nextReject("Unsupported command: " + getCommandStringId(command) + ". Set spindle and coolant in the Fusion operation."); }
}
function onSectionEnd() { nextSection = undefined; nextOperationLabel = ""; }
function onClose() {
  nextGuard(function () {
    // Nothing is emitted before the entire program has been accepted.
    var output = nextProgram.toSTEP().split("\n");
    for (var i = 0; i < output.length - 1; ++i) { writeln(output[i]); }
    nextLog("NEXTNC OUTPUT WRITTEN " + JSON.stringify({release: NextNC.version, callbacks: nextEventCount,
      sections: getNumberOfSections(), lines: output.length - 1}));
  });
}

// Explicit entry-point wrapping also catches failures outside nextGuard.
onOpen = nextCallback("onOpen", onOpen);
onSection = nextCallback("onSection", onSection);
onRapid = nextCallback("onRapid", onRapid);
onLinear = nextCallback("onLinear", onLinear);
onCircular = nextCallback("onCircular", onCircular);
onDwell = nextCallback("onDwell", onDwell);
onFeedMode = nextCallback("onFeedMode", onFeedMode);
onSpindleSpeed = nextCallback("onSpindleSpeed", onSpindleSpeed);
onRadiusCompensation = nextCallback("onRadiusCompensation", onRadiusCompensation);
onToolCompensation = nextCallback("onToolCompensation", onToolCompensation);
onCycle = nextCallback("onCycle", onCycle);
onCyclePoint = nextCallback("onCyclePoint", onCyclePoint);
onCyclePath = nextCallback("onCyclePath", onCyclePath);
onLinear5D = nextCallback("onLinear5D", onLinear5D);
onRapid5D = nextCallback("onRapid5D", onRapid5D);
onPassThrough = nextCallback("onPassThrough", onPassThrough);
onManualNC = nextCallback("onManualNC", onManualNC);
onOrientateSpindle = nextCallback("onOrientateSpindle", onOrientateSpindle);
onMachineCommand = nextCallback("onMachineCommand", onMachineCommand);
onSectionSpecialCycle = nextCallback("onSectionSpecialCycle", onSectionSpecialCycle);
onSpecialCycle = nextCallback("onSpecialCycle", onSpecialCycle);
onPower = nextCallback("onPower", onPower);
onLiveAlignment = nextCallback("onLiveAlignment", onLiveAlignment);
onCommand = nextCallback("onCommand", onCommand);
onSectionEnd = nextCallback("onSectionEnd", onSectionEnd);
onClose = nextCallback("onClose", onClose);
