"use strict";
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const output = "// Generated by npm run build. Edit src/next-nc.js and src/fusion-adapter.js.\n" +
  ["next-nc.js", "fusion-adapter.js"].map(file => fs.readFileSync(path.join(root, "src", file), "utf8").replace(/\r\n/g, "\n")).join("\n");
const target = path.join(root, "posts", "next-nc.cps");
if (process.argv.includes("--check")) {
  if (!fs.existsSync(target) || fs.readFileSync(target, "utf8").replace(/\r\n/g, "\n") !== output) {
    throw new Error("Generated CPS is stale. Run npm run build.");
  }
} else { fs.mkdirSync(path.dirname(target), {recursive: true}); fs.writeFileSync(target, output); }
